
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Wed Jun 02 13:30:58 CST 2021
//----------------------------------------------------

package analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int FINLLAVE = 28;
  public static final int DOSPTO = 23;
  public static final int DISTINTO = 6;
  public static final int ASIGNAR = 4;
  public static final int ABRECORCHETE = 24;
  public static final int ENTERO = 16;
  public static final int RESTA = 14;
  public static final int LPAREN = 19;
  public static final int SEMI = 17;
  public static final int FOR = 36;
  public static final int RPAREN = 20;
  public static final int IDENTIFICADOR = 3;
  public static final int MENORIGUAL = 8;
  public static final int AND = 12;
  public static final int IGUAL = 5;
  public static final int OR = 11;
  public static final int SUMA = 13;
  public static final int PLUS = 18;
  public static final int IF = 29;
  public static final int INICIOLLAVE = 27;
  public static final int PTOCOMA = 21;
  public static final int MAYORIGUAL = 10;
  public static final int EOF = 0;
  public static final int PTO = 22;
  public static final int error = 1;
  public static final int COMA = 26;
  public static final int MENOR = 7;
  public static final int NUMBER = 37;
  public static final int CIERRACORCHETE = 25;
  public static final int BREAK = 32;
  public static final int SWITCH = 35;
  public static final int MAYOR = 9;
  public static final int TIMES = 15;
  public static final int PUTS = 33;
  public static final int ELSE = 30;
  public static final int CADENATEXTO = 2;
  public static final int WHILE = 31;
  public static final int SET = 34;
}

